#!/bin/bash
# Crypto Trading Bot - Secure Setup Script
# Dieses Skript hilft beim sicheren Setup der Umgebungsvariablen

set -e

echo "🤖 Crypto Trading Bot - Secure Setup"
echo "======================================"
echo ""

# Check if .env.local already exists
if [ -f ".env.local" ]; then
    echo "⚠️  .env.local already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo "Setup aborted."
        exit 0
    fi
fi

echo "📝 Please provide your configuration details:"
echo ""

# Telegram Bot Token
echo "🤖 TELEGRAM BOT CONFIGURATION"
echo "   Get your bot token from @BotFather on Telegram"
read -p "Telegram Bot Token: " telegram_token

# Telegram Chat ID
echo ""
echo "💬 To get your Chat ID:"
echo "   1. Message your bot first"
echo "   2. Visit: https://api.telegram.org/bot<YOUR_BOT_TOKEN>/getUpdates"
echo "   3. Look for 'chat':{'id': YOUR_CHAT_ID}"
read -p "Telegram Chat ID: " telegram_chat_id

# Web Configuration
echo ""
echo "🌐 WEB CONFIGURATION"
read -p "Web Host (default: 0.0.0.0): " web_host
web_host=${web_host:-0.0.0.0}

read -p "Web Port (default: 5000): " web_port
web_port=${web_port:-5000}

# Database
echo ""
echo "🗄️  DATABASE CONFIGURATION"
read -p "Database Path (default: crypto_trading_bot.db): " db_path
db_path=${db_path:-crypto_trading_bot.db}

# Monitoring settings
echo ""
echo "⏰ MONITORING CONFIGURATION"
read -p "Arbitrage Check Interval in seconds (default: 60): " arbitrage_interval
arbitrage_interval=${arbitrage_interval:-60}

read -p "Performance Check Interval in seconds (default: 1200): " performance_interval
performance_interval=${performance_interval:-1200}

read -p "Number of cryptocurrencies to analyze (default: 100): " crypto_count
crypto_count=${crypto_count:-100}

# Alert settings
echo ""
echo "🚨 ALERT CONFIGURATION"
read -p "Arbitrage Threshold in % (default: 1.5): " arbitrage_threshold
arbitrage_threshold=${arbitrage_threshold:-1.5}

# Create .env.local file
cat > .env.local << EOF
# Crypto Trading Bot 24/7 - LOCAL Environment Variables
# Auto-generated by setup script on $(date)

# =============================================================================
# TELEGRAM BOT CONFIGURATION
# =============================================================================
TELEGRAM_BOT_TOKEN=$telegram_token
TELEGRAM_CHAT_ID=$telegram_chat_id

# =============================================================================
# DATABASE CONFIGURATION  
# =============================================================================
DATABASE_PATH=$db_path

# =============================================================================
# WEB API CONFIGURATION
# =============================================================================
WEB_HOST=$web_host
WEB_PORT=$web_port

# =============================================================================
# MONITORING CONFIGURATION
# =============================================================================
ARBITRAGE_CHECK_INTERVAL=$arbitrage_interval
PERFORMANCE_CHECK_INTERVAL=$performance_interval
DAILY_SUMMARY_HOUR=8
ANALYSIS_CRYPTO_COUNT=$crypto_count

# =============================================================================
# ALERT CONFIGURATION  
# =============================================================================
ARBITRAGE_THRESHOLD=$arbitrage_threshold
SHARPE_CHANGE_THRESHOLD=0.5
ALERT_COOLDOWN_MINUTES=10

# =============================================================================
# WATCHLIST CONFIGURATION
# =============================================================================
WATCHLIST_SYMBOLS=BTC/USDT,ETH/USDT,BNB/USDT,ADA/USDT,DOT/USDT

# =============================================================================
# EXCHANGES CONFIGURATION
# =============================================================================
EXCHANGES=binance,coinbase,kraken

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOG_LEVEL=INFO
LOG_FILE=
EOF

echo ""
echo "✅ Configuration saved to .env.local"
echo ""
echo "🔒 SECURITY NOTE:"
echo "   - Your .env.local file contains sensitive data"
echo "   - It's automatically excluded from git commits"
echo "   - Never share your bot token or chat ID"
echo ""
echo "🚀 Next steps:"
echo "   make test      # Run all tests"
echo "   make dev       # Start development environment"
echo "   make deploy    # Deploy to production"
echo ""
echo "📊 Dashboard will be available at: http://$web_host:$web_port"
echo ""
echo "Happy Trading! 🤖💹"
